<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use App\Scopes\VariationActiveScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class ProductVariation extends Model
{
    use SoftDeletes;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new VariationActiveScope());
    }

    protected $fillable = [
        'product_id',
        'title',
        'current_price',
        'currency',
        'price_max',
        'price_min',
        'availability',
        'condition',
        'color',
        'size',
        'merchant',
        'source_url',
        'source_id',
    ];

    protected $casts = [
        'status' => 'boolean'
    ];

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }

    public function source()
    {
        return $this->belongsTo(Source::class, 'source_id', 'id');
    }

    public function sourceWithoutScope()
    {
        return $this->source()->withoutGlobalScopes();
    }
}
