<?php

namespace App\Models;

use App\Observers\SourceObserver;
use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Source extends Model implements HasMedia
{
    use HasMediaTrait;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ActiveScope());
        self::observe(SourceObserver::class);
    }

    protected $fillable = ['name', 'status'];

    protected $casts = [
        'status' => 'boolean'
    ];

    public function variations()
    {
        return $this->hasMany(ProductVariation::class, 'source_id', 'id');
    }

    public function generateUrl()
    {
        return 'https://' . $this->name;
    }
}
